# Generated by Django 6.0 on 2025-12-13 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(help_text='Unique ID (e.g., RISK-001)', max_length=20, unique=True)),
                ('area_name', models.CharField(blank=True, help_text='Department or Area (e.g. IT, Finance)', max_length=100, null=True)),
                ('description', models.TextField(verbose_name='Risk Description')),
                ('caused_by', models.TextField(blank=True, default='', help_text='What triggers this risk?', verbose_name='Root Cause')),
                ('consequences', models.TextField(blank=True, default='', help_text='What happens if this risk occurs?', verbose_name='Consequences')),
                ('risk_owner', models.CharField(help_text='Person responsible for this risk', max_length=100)),
                ('inherent_probability', models.CharField(choices=[('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Very Low', 'Very Low')], max_length=20)),
                ('inherent_impact', models.CharField(choices=[('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Very Low', 'Very Low')], max_length=20)),
                ('inherent_rating', models.CharField(blank=True, choices=[('Critical', 'Critical'), ('Severe', 'Severe'), ('Moderate', 'Moderate'), ('Sustainable', 'Sustainable')], editable=False, max_length=20)),
                ('controls', models.TextField(blank=True, verbose_name='Control Descriptions')),
                ('control_owner', models.CharField(blank=True, max_length=100)),
                ('residual_probability', models.CharField(choices=[('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Very Low', 'Very Low')], max_length=20)),
                ('residual_impact', models.CharField(choices=[('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Very Low', 'Very Low')], max_length=20)),
                ('residual_rating', models.CharField(blank=True, choices=[('Critical', 'Critical'), ('Severe', 'Severe'), ('Moderate', 'Moderate'), ('Sustainable', 'Sustainable')], editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
