# Generated by Django 6.0 on 2026-01-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0003_aisettings_alter_reportconfiguration_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aisettings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reportconfiguration',
            options={'verbose_name': 'Report Settings'},
        ),
    ]
