# Generated by Django 6.0 on 2026-01-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0004_alter_aisettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='risk_coordinator_name',
            field=models.CharField(blank=True, default='', help_text='Coordinator responsible for follow-up / reporting', max_length=100),
        ),
    ]
