# Generated by Django 6.0 on 2026-04-08 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0005_riskassessment_risk_coordinator_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='max_context_risks',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='model_name',
            field=models.CharField(default='gpt-4.1-mini', max_length=100),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='provider',
            field=models.CharField(default='openai', max_length=30),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='system_prompt',
            field=models.TextField(default='You are a bank compliance copilot. Answer only from the grounded system context provided. Do not invent facts, do not claim to have checked records that are not in the context, and make your uncertainty explicit whenever the system data is incomplete.'),
        ),
        migrations.CreateModel(
            name='AIAssistantAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='openai', max_length=30)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('grounded_context', models.JSONField(blank=True, default=dict)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('used_live_llm', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('success', 'Success'), ('fallback', 'Fallback'), ('error', 'Error')], default='fallback', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('response_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_assistant_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Assistant Audit Log',
                'verbose_name_plural': 'AI Assistant Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
