# Generated by Django 6.0 on 2026-06-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0006_aisettings_max_context_risks_aisettings_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='action_due_date',
            field=models.DateField(blank=True, help_text='Target completion date for the mitigation action.', null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='action_last_update',
            field=models.TextField(blank=True, default='', help_text='Latest management update on the action plan.', verbose_name='Action Progress Update'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='action_progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='Completion progress from 0 to 100 percent.'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='action_responsible_officer',
            field=models.CharField(blank=True, default='', help_text='Officer responsible for completing the mitigation action.', max_length=100),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='action_status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Deferred', 'Deferred')], default='Not Started', max_length=20),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='mitigation_action',
            field=models.TextField(blank=True, default='', help_text='Specific action management will take to reduce or control this risk.', verbose_name='Mitigation Action Plan'),
        ),
    ]
