# Generated by Django 6.0 on 2026-06-17 09:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0007_remove_aisettings_max_context_risks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskTrendSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(default=django.utils.timezone.localdate)),
                ('area_name', models.CharField(blank=True, default='', max_length=100)),
                ('inherent_probability', models.CharField(max_length=20)),
                ('inherent_impact', models.CharField(max_length=20)),
                ('inherent_rating', models.CharField(max_length=20)),
                ('residual_probability', models.CharField(max_length=20)),
                ('residual_impact', models.CharField(max_length=20)),
                ('residual_rating', models.CharField(max_length=20)),
                ('action_status', models.CharField(blank=True, default='', max_length=20)),
                ('action_progress', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_snapshots', to='risks.riskassessment')),
            ],
            options={
                'verbose_name': 'Risk Trend Snapshot',
                'verbose_name_plural': 'Risk Trend Snapshots',
                'ordering': ['-snapshot_date', 'risk__reference_id'],
                'unique_together': {('risk', 'snapshot_date')},
            },
        ),
    ]
