# Generated by Django 6.0 on 2026-06-17 09:11

from django.db import migrations, models


def set_existing_drafts(apps, schema_editor):
    RiskAssessment = apps.get_model('risks', 'RiskAssessment')
    RiskAssessment.objects.filter(description__startswith='[DRAFT]').update(workflow_status='Draft')


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0009_systemauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='workflow_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Reviewed', 'Reviewed'), ('Approved', 'Approved'), ('Closed', 'Closed')], default='Approved', help_text='Approval stage for this risk record.', max_length=20),
        ),
        migrations.RunPython(set_existing_drafts, migrations.RunPython.noop),
    ]
