# Generated by Django 6.0 on 2026-06-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0010_riskassessment_workflow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='escalation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='escalation_status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Management Attention', 'Management Attention'), ('Board Attention', 'Board Attention')], default='Normal', max_length=30),
        ),
    ]
