# Generated by Django 6.0 on 2026-06-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0011_riskassessment_escalated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='control_effectiveness',
            field=models.CharField(choices=[('Not Assessed', 'Not Assessed'), ('Strong', 'Strong'), ('Moderate', 'Moderate'), ('Weak', 'Weak')], default='Not Assessed', max_length=20),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='control_effectiveness_rationale',
            field=models.TextField(blank=True, default=''),
        ),
    ]
