# Generated by Django 6.0 on 2026-06-17 09:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0012_riskassessment_control_effectiveness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField(default=django.utils.timezone.localdate)),
                ('area_name', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('root_cause', models.TextField(blank=True, default='')),
                ('loss_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Investigating', 'Investigating'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('reported_by', models.CharField(blank=True, default='', max_length=100)),
                ('action_taken', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='risks.riskassessment')),
            ],
            options={
                'verbose_name': 'Loss / Incident',
                'verbose_name_plural': 'Loss / Incident Register',
                'ordering': ['-incident_date', '-created_at'],
            },
        ),
    ]
