# Generated by Django 6.0 on 2026-06-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0013_riskincident'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='action_responsible_email',
            field=models.EmailField(blank=True, default='', help_text='Email address for due-date and overdue action reminders.', max_length=254),
        ),
    ]
