# Generated by Django 6.0 on 2026-07-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0015_alter_riskassessment_moderate_choice_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='customer_profile_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='customer_profile_rating',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='customer_profile_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
