# Generated by Django 6.0 on 2026-07-08 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0016_riskassessment_customer_profile_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(blank=True, default='', max_length=80)),
                ('account_name', models.CharField(blank=True, default='', max_length=200)),
                ('profile_rating', models.CharField(blank=True, default='', max_length=20)),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('total_score', models.PositiveSmallIntegerField(default=0)),
                ('determinant_count', models.PositiveSmallIntegerField(default=0)),
                ('determinants', models.JSONField(blank=True, default=list)),
                ('recommendation', models.TextField(blank=True, default='')),
                ('enhanced_due_diligence', models.TextField(blank=True, default='')),
                ('confidence_notes', models.TextField(blank=True, default='')),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('source_type', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profiles_created', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profiles', to='risks.riskassessment')),
            ],
            options={
                'verbose_name': 'Customer Risk Profile',
                'verbose_name_plural': 'Customer Risk Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
