# Generated by Django 6.0 on 2026-07-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0017_customerriskprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerriskprofile',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='customer_profiles/'),
        ),
        migrations.AddField(
            model_name='customerriskprofile',
            name='movement',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customerriskprofile',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerriskprofile',
            name='previous_average_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='customerriskprofile',
            name='previous_rating',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customerriskprofile',
            name='review_frequency',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
