# Generated by Codex for the bank Low/Medium/High risk scale

from django.db import migrations, models


def normalize_level(value):
    value = (value or "").strip()
    if value in ["Very High", "High", "Critical"]:
        return "High"
    if value in ["Medium", "Moderate", "Severe"]:
        return "Medium"
    return "Low"


def rank_for(probability, impact):
    weights = {"Low": 1, "Medium": 2, "High": 3}
    score = weights[normalize_level(probability)] * weights[normalize_level(impact)]
    if score >= 9:
        return "High"
    if score >= 3:
        return "Medium"
    return "Low"


def migrate_existing_ratings(apps, schema_editor):
    RiskAssessment = apps.get_model("risks", "RiskAssessment")
    RiskTrendSnapshot = apps.get_model("risks", "RiskTrendSnapshot")

    for risk in RiskAssessment.objects.all():
        risk.inherent_probability = normalize_level(risk.inherent_probability)
        risk.inherent_impact = normalize_level(risk.inherent_impact)
        risk.residual_probability = normalize_level(risk.residual_probability)
        risk.residual_impact = normalize_level(risk.residual_impact)
        risk.inherent_rating = rank_for(risk.inherent_probability, risk.inherent_impact)
        risk.residual_rating = rank_for(risk.residual_probability, risk.residual_impact)
        if risk.control_effectiveness == "Moderate":
            risk.control_effectiveness = "Medium"
        risk.save(update_fields=[
            "inherent_probability",
            "inherent_impact",
            "inherent_rating",
            "residual_probability",
            "residual_impact",
            "residual_rating",
            "control_effectiveness",
        ])

    for snapshot in RiskTrendSnapshot.objects.all():
        snapshot.inherent_rating = normalize_level(snapshot.inherent_rating)
        snapshot.residual_rating = normalize_level(snapshot.residual_rating)
        snapshot.save(update_fields=["inherent_rating", "residual_rating"])


class Migration(migrations.Migration):

    dependencies = [
        ("risks", "0018_customerriskprofile_evidence_file_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_existing_ratings, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="riskassessment",
            name="inherent_probability",
            field=models.CharField(choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")], max_length=20),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="inherent_impact",
            field=models.CharField(choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")], max_length=20),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="inherent_rating",
            field=models.CharField(blank=True, choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")], editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="residual_probability",
            field=models.CharField(choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")], max_length=20),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="residual_impact",
            field=models.CharField(choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")], max_length=20),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="residual_rating",
            field=models.CharField(blank=True, choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")], editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="control_effectiveness",
            field=models.CharField(choices=[("Not Assessed", "Not Assessed"), ("Strong", "Strong"), ("Medium", "Medium"), ("Weak", "Weak")], default="Not Assessed", max_length=20),
        ),
    ]
